server:
  port: 8081

spring:
  redis:
    timeout: 10000ms
    host: localhost
    port: 6379
    database: 0 # 选择哪个库，默认0库
    lettuce:
      pool:
        max-active: 1024 # 最大连接数，默认 8
        max-wait: 10000ms # 最大连接阻塞等待时间，单位毫秒，默认 -1
        max-idle: 200 # 最大空闲连接，默认 8
        min-idle: 5
  datasource:
    username: root
    password:
    url: jdbc:mysql://127.0.0.1:3306/data_cloud?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
# Mybatis-plus配置
mybatis-plus:
  #配置Mapper映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置MyBatis数据返回类型别名（默认别名是类名）
  type-aliases-package: com.project.data_cloud_server.entity
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: false
## Mybatis SQL 打印(方法接口所在的包，不是Mapper.xml所在的包)
logging:
  level:
    com.project.data_cloud_server.mapper: debug
  file:
    path: /www/data_cloud/data_cloud_back/logs
jwt:
  # JWT存储的请求头
  tokenHeader: Authorization
  # JWT 加解密使用的密钥
  secret: yy-secret
  # JWT的超期限时间（60*60*1）
  expiration: 3600
  # JWT 负载中拿到开头
  tokenHead: Bearer
